src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\RoleEnum;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[UniqueEntity(fields: ['email'], message: 'Cet email est déjà utilisé.')]
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id_user', type: 'integer')]
    private ?int $id_user = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $mdp = null;

    #[ORM\Column(type: 'integer')]
    private $tel;

    #[ORM\Column(type: 'string', length: 30)]
    private string $role;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\OneToMany(targetEntity: Favoris::class, mappedBy: 'user', cascade: ['remove'])]
    private Collection $favoris;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $resetToken = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $resetTokenExpiresAt = null;
    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
private ?\DateTimeImmutable $lastLoginAt = null;

#[ORM\Column(type: 'datetime_immutable', nullable: true)]
private ?\DateTimeImmutable $lastLogoutAt = null;

#[ORM\Column(type: 'integer')]
private int $totalSessionTime = 0; // in seconds

#[ORM\Column(type: 'integer')]
private int $loginCount = 0;
    public function __construct()
    {
        $this->favoris = new ArrayCollection();
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;
        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): static
    {
        $this->mdp = $mdp;
        return $this;
    }

    public function getTel(): ?int
    {
        return $this->tel;
    }

    public function setTel(int $tel): static
    {
        $this->tel = $tel;
        return $this;
    }

    public function getRole(): RoleEnum
    {
        return RoleEnum::from($this->role);
    }

    public function setRole(RoleEnum $role): static
    {
        $this->role = $role->value;
        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;
        return $this;
    }

    public function getRoles(): array
    {
        return [$this->getRole()->value];
    }

    public function setRoles(array $roles): static
    {
        if (!empty($roles)) {
            $roleValue = $roles[0];
            if (RoleEnum::tryFrom($roleValue)) {
                $this->setRole(RoleEnum::from($roleValue));
            }
        }
        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getPassword(): string
    {
        return $this->mdp;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Favoris $favori): static
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris->add($favori);
            $favori->setUser($this);
        }
        return $this;
    }

    public function removeFavori(Favoris $favori): static
    {
        if ($this->favoris->removeElement($favori)) {
            if ($favori->getUser() === $this) {
                $favori->setUser(null);
            }
        }
        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): static
    {
        $this->resetToken = $resetToken;
        return $this;
    }

    public function getResetTokenExpiresAt(): ?\DateTimeImmutable
    {
        return $this->resetTokenExpiresAt;
    }

    public function setResetTokenExpiresAt(?\DateTimeImmutable $resetTokenExpiresAt): static
    {
        $this->resetTokenExpiresAt = $resetTokenExpiresAt;
        return $this;
    }

    public function isResetTokenValid(): bool
    {
        return $this->resetTokenExpiresAt !== null && 
               $this->resetTokenExpiresAt > new \DateTimeImmutable();
    }

    public function __toString(): string
    {
        return $this->prenom . ' ' . $this->nom;
    }
    
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Form\UserRegisterType;
use App\Form\UserEditType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use App\Repository\UserRepository;  // Make sure this is the correct namespace for your UserRepository
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Knp\Component\Pager\PaginatorInterface;
use App\Repository\FavorisRepository;
use App\Entity\Favoris;
use Dompdf\Dompdf;
use Dompdf\Options;
class UserController extends AbstractController
{
    private $userRepository;
    private $tokenStorage;

    public function __construct(UserRepository $userRepository, TokenStorageInterface $tokenStorage)
    {
        $this->userRepository = $userRepository;
        $this->tokenStorage = $tokenStorage;
    }

    #[Route('/user/create', name: 'user_create')]
    public function create(Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $plainPassword = $form->get('mdp')->getData();
                $hashedPassword = $passwordHasher->hashPassword($user, $plainPassword);
                $user->setMdp($hashedPassword);

                /** @var UploadedFile $imageFile */
                $imageFile = $form->get('image')->getData();

                if ($imageFile) {
                    $newFilename = uniqid() . '.' . $imageFile->guessExtension();

                    try {
                        $imageFile->move(
                            $this->getParameter('uploads_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        $this->addFlash('error', 'Erreur lors du téléchargement de l\'image.');
                    }

                    $user->setImage($newFilename);
                }

                $em->persist($user);
                $em->flush();

                $this->addFlash('success', 'Utilisateur créé avec succès !');
                return $this->redirectToRoute('user_list');
            } else {
                $this->addFlash('error', 'Veuillez corriger les erreurs du formulaire.');
            }
        }

        return $this->render('user/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    #[Route('/user/register', name: 'user_register')]
public function register(Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $passwordHasher): Response
{
    $user = new User();
    $form = $this->createForm(UserRegisterType::class, $user);
    $form->handleRequest($request);

    if ($form->isSubmitted()) {
        if ($form->isValid()) {
            $plainPassword = $form->get('mdp')->getData();
            $hashedPassword = $passwordHasher->hashPassword($user, $plainPassword);
            $user->setMdp($hashedPassword);

            // ✅ Set default role
            $user->setRoles(['ROLE_USER']);

            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('image')->getData();

            if ($imageFile) {
                $newFilename = uniqid() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('uploads_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('error', 'Erreur lors du téléchargement de l\'image.');
                }

                $user->setImage($newFilename);
            }

            $em->persist($user);
            $em->flush();

            $this->addFlash('success', 'Utilisateur créé avec succès !');
            return $this->redirectToRoute('app_login');
        } else {
            $this->addFlash('error', 'Veuillez corriger les erreurs du formulaire.');
        }
    }

    return $this->render('user/register.html.twig', [
        'form' => $form->createView(),
    ]);
}

    #[Route('/user/{id}/edit', name: 'user_edit')]
    public function edit(Request $request, User $user, EntityManagerInterface $em)
{
    $form = $this->createForm(UserType::class, $user);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // Save the user if the form is valid
        $em->flush();
        return $this->redirectToRoute('user_list');
    }

    // Render the form with error messages if not valid
    return $this->render('user/edit.html.twig', [
        'form' => $form->createView(),
    ]);
}


#[Route('/user/modifier', name: 'user_modifier')]
public function modifier(
    Request $request,
    EntityManagerInterface $em,
    UserPasswordHasherInterface $passwordHasher
): Response {
    $user = $this->getUser();

    if (!$user) {
        throw $this->createAccessDeniedException('Vous devez être connecté pour modifier votre profil.');
    }

    // If the user is an admin, redirect to the admin modification route
    if (in_array('ROLE_ADMIN', $user->getRoles())) {
        return $this->redirectToRoute('user_modifieradmin');
    }

    // Normal user form
    $form = $this->createForm(UserEditType::class, $user);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $imageFile = $form->get('image')->getData();

        if ($imageFile) {
            $newFilename = uniqid() . '.' . $imageFile->guessExtension();
            $imageFile->move($this->getParameter('uploads_directory'), $newFilename);
            $user->setImage($newFilename);
        }

        $em->flush();
        $this->addFlash('success', 'Compte modifié avec succès !');

        return $this->redirectToRoute('app_profile');
    }

    return $this->render('user/modifier.html.twig', [
        'form' => $form->createView(),
        'user' => $user,
    ]);
}


    #[Route('/user/modifieradmin', name: 'user_modifieradmin')]
public function modifieradmin(Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $passwordHasher): Response
{
    $user = $this->getUser();
    if (!$user) {
        throw $this->createAccessDeniedException('Vous devez être connecté pour modifier votre profil.');
    }

    $originalPassword = $user->getMdp();
    $originalImage = $user->getImage();

    $form = $this->createForm(UserEditType::class, $user);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $newPassword = $form->get('mdp')->getData();
        if ($newPassword) {
            $hashed = $passwordHasher->hashPassword($user, $newPassword);
            $user->setMdp($hashed);
        } else {
            $user->setMdp($originalPassword);
        }

        /** @var UploadedFile $imageFile */
        $imageFile = $form->get('image')->getData();
        if ($imageFile) {
            $newFilename = uniqid() . '.' . $imageFile->guessExtension();
            $imageFile->move($this->getParameter('uploads_directory'), $newFilename);
            $user->setImage($newFilename);
        } else {
            $user->setImage($originalImage);
        }

        $em->flush();
        $this->addFlash('success', 'Compte modifié avec succès !');
        return $this->redirectToRoute('app_profile_admin');
    }

    return $this->render('user/modifieradmin.html.twig', [
        'form' => $form->createView(),
        'user' => $user,
    ]);
}


    #[Route('/user/show/{id}', name: 'user_show', requirements: ['id' => '\d+'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/users', name: 'user_list')]
public function listUsers(Request $request, EntityManagerInterface $em, PaginatorInterface $paginator): Response
{
    $roleFilter = $request->query->get('role');

    $qb = $em->getRepository(User::class)->createQueryBuilder('u');

    if ($roleFilter) {
        $qb->andWhere('u.role = :role')
           ->setParameter('role', $roleFilter);
    }

    $query = $qb->getQuery();

    $pagination = $paginator->paginate(
        $query,
        $request->query->getInt('page', 1),
        10
    );

    return $this->render('user/list.html.twig', [
        'users' => $pagination,
        'currentRole' => $roleFilter,
    ]);
}

#[Route('/delete-user/{id}', name: 'user_delete')]
public function deleteUser(
    int $id,
    EntityManagerInterface $em,
    TokenStorageInterface $tokenStorage,
    Request $request
): RedirectResponse {
    $userToDelete = $em->getRepository(User::class)->find($id);

    if (!$userToDelete) {
        throw $this->createNotFoundException('Utilisateur non trouvé.');
    }

    $currentUser = $this->getUser();

    // Check if the current user is deleting themselves
    $isSelf = $currentUser && $userToDelete->getIdUser() === $currentUser->getIdUser();

    // Remove user
    $em->remove($userToDelete);
    $em->flush();

    if ($isSelf) {
        // Manually log the user out
        $tokenStorage->setToken(null);
        $request->getSession()->invalidate();

        return $this->redirectToRoute('app_login');
    }

    return $this->redirectToRoute('user_list');
}

    
    #[Route('/delete-my-account', name: 'user_delete_self')]

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/jihen/Downloads/Noujoum-Symfony/src/Controller/UserController.php</code></li>
        <li>Your template at <code>C:/Users/jihen/Downloads/Noujoum-Symfony/templates/user/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <style>
        body {
            background-color: #2c2c2c;
            color: #f0f0f0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .profile-container {
            margin-top: 60px;
            display: flex;
            justify-content: center;
        }

        .card {
            background-color: #3a3a3a;
            border: 2px solid #d4af37;
            border-radius: 15px;
            padding: 40px;
            width: 100%;
            max-width: 600px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.3);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 0 25px rgba(0, 0, 0, 0.4);
        }

        .profile-header .profile-image {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 50%;
            border: 4px solid #d4af37;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }

        .profile-header .profile-image:hover {
            transform: scale(1.05);
            box-shadow: 0 0 10px #d4af37;
        }

        .profile-name {
            font-size: 1.8rem;
            font-weight: bold;
            color: #f0f0f0;
        }

        .profile-role {
            font-size: 1rem;
            margin-top: 5px;
            color: #ccc;
        }

        .info-section {
            margin-top: 30px;
        }

        .info-section p {
            font-size: 1.1rem;
            margin-bottom: 0.5rem;
        }

        .custom-btn {
            background-color: transparent;
            border: 2px solid #d4af37;
            color: #d4af37;
            padding: 0.5rem 1.2rem;
            font-weight: 500;
            transition: all 0.3s ease;
            border-radius: 30px;
        }

        .custom-btn:hover {
            background-color: #d4af37;
            color: #000;
            transform: scale(1.05);
        }

        .custom-btn.danger {
            border-color: #ff4d4d;
            color: #ff4d4d;
        }

        .custom-btn.danger:hover {
            background-color: #ff4d4d;
            color: #fff;
        }

        .actions {
            margin-top: 30px;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            gap: 20px;
        }

        .alert {
            color: #fff;
            background-color: #a94442;
            border: none;
        }
    </style>
{% endblock %}

{% block body %}
<div class="container profile-container">
    <div class="card text-center">
        {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
        {% elseif user %}
            <div class="profile-header mb-4">
                {% if user.image %}
                    <img src="{{ asset('uploads/' ~ user.image) }}" alt="Photo de profil" class="profile-image">
                {% else %}
                    <img src="{{ asset('uploads/user.png') }}" alt="Photo de profil par défaut" class="profile-image">
                {% endif %}
                <h2 class="profile-name mt-3">{{ user.prenom }} {{ user.nom }}</h2>
                <div class="profile-role">
                    {% if 'ROLE_ADMIN' in user.roles %}
                        Admin
                    {% elseif 'ROLE_USER' in user.roles %}
                        Fan
                    {% elseif 'ROLE_ARTIST' in user.roles %}
                        Artiste
                    {% else %}
                        Inconnu
                    {% endif %}
                </div>
            </div>

            <div class="info-section mb-4">
                <p><strong>Email :</strong> {{ user.email }}</p>
                <p><strong>Téléphone :</strong> {{ user.tel }}</p>
                <p><strong>Adresse :</strong> Esprit bloc IJK</p>
            </div>

            <div class="actions">
                <a href="{{ path('user_modifier', {'id': user.idUser}) }}" class="btn custom-btn">
                    <i class="fas fa-edit"></i> Modifier le compte
                </a>

                <form method="post" action="{{ path('user_delete_self') }}" class="d-inline" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer votre compte ?');">
                    <button type="submit" class="btn custom-btn danger">
                        <i class="fas fa-user-slash"></i> Supprimer mon compte
                    </button>
                </form>

                <form method="post" action="{{ path('app_logout') }}" class="d-inline">
                    <button type="submit" class="btn custom-btn">
                        <i class="fas fa-sign-out-alt"></i> Se déconnecter
                    </button>
                </form>
            </div>
        {% else %}
            <div class="text-center text-light">Aucun utilisateur trouvé.</div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/user/profileadmin.html.twig
{% extends 'backoffice.html.twig' %}

{% block head %}
<!-- FontAwesome for icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap');

    body {
        font-family: 'Poppins', sans-serif;
        background-color: #3a3a3a; /* Darker gray background for the page */
        margin: 0;
        padding: 0;
    }

    .profile-container {
        max-width: 700px;
        margin: 40px auto;
        padding: 30px;
        border-radius: 12px;
        background-color: #505050; /* Dark gray for the profile card */
        border: 2px solid #d4af37; /* Thinner gold border around the profile card */
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3); /* Finer, shinier effect */
        transition: transform 0.3s ease-in-out; /* Smooth transition for movement */
    }

    .profile-container:hover {
    transform: translateY(-10px);
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.4); /* Deeper shadow on hover */
    }


    .profile-header {
        text-align: center;
        margin-bottom: 20px;
    }

    .profile-image {
        width: 140px;
        height: 140px;
        object-fit: cover;
        border-radius: 50%;
        border: 2px solid #d4af37; /* Gold border around the image */
        margin-bottom: 15px;
        box-shadow: 0 4px 10px rgba(0,0,0,0.2);
        transition: transform 0.3s ease-in-out;
    }
    .profile-image:hover {
    transform: scale(1.1); /* Subtle zoom effect on hover */
     }
    .profile-name {
        font-size: 24px;
        font-weight: 600;
        color: #f4f4f4; /* Light font color to contrast with the dark background */
    }

    .profile-role {
        display: inline-block;
        background-color: #d4af37; /* Gold */
        color: white;
        padding: 6px 12px;
        border-radius: 20px;
        font-size: 16px;
        margin-top: 10px;
    }

    .info-section {
        margin-top: 20px;
    }

    .info-section p {
        font-size: 16px;
        color: #ddd; /* Lighter text for readability */
        margin-bottom: 10px;
    }

    .address {
        color: #bbb;
        font-style: italic;
    }

    .btn {
        padding: 12px 25px;
        font-size: 16px;
        font-weight: 600;
        transition: all 0.3s ease;
        border-radius: 30px;
        border: none;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px; /* Space between icon and text */
        transition: background-color 0.3s ease, transform 0.3s ease;
    }

    .btn-primary {
        background-color: #d4af37; /* Gold button */
        color: white;
        border-radius: 30px;
        border: 2px solid #d4af37; /* Gold border */
    }

    .btn-primary:hover {
        background-color: #f4d03f; /* Lighter gold on hover */
    }

    .btn-danger {
        background-color: #8e4b3b; /* Elegant maroon (muted red) for "Supprimer" button */
        color: white;
        border-radius: 30px;
        border: 2px solid #8e4b3b; /* Muted red border */
    }

    .btn-danger:hover {
        background-color: #a85c4b; /* Slightly lighter maroon on hover */
    }

    .btn:hover {
        transform: scale(1.05);
    }

    .actions {
        display: flex;
        justify-content: center;
        gap: 20px;
        margin-top: 30px;
    }
    
</style>
{% endblock %}

{% block body %}
<div class="container profile-container">
    {% if error %}
        <div class="alert alert-danger text-center">{{ error }}</div>
    {% elseif user %}
        <div class="profile-header">
            {% if user.image %}
                <img src="{{ asset('uploads/' ~ user.image) }}" alt="Photo de profil" class="profile-image">
            {% else %}
                <img src="{{ asset('uploads/user.png') }}" alt="Photo de profil par défaut" class="profile-image">
            {% endif %}
            <div class="profile-name">{{ user.prenom }} {{ user.nom }}</div>
            <div class="profile-role">
                {% if 'ROLE_ADMIN' in user.roles %}
                    Admin
                {% elseif 'ROLE_USER' in user.roles %}
                    Fan
                {% elseif 'ROLE_ARTIST' in user.roles %}
                    Artiste
                {% else %}
                    Inconnu
                {% endif %}
            </div>
        </div>

        <div class="info-section">
            <p><strong>Email :</strong> {{ user.email }}</p>
            <p><strong>Téléphone :</strong> {{ user.tel }}</p>
            <p><strong>Adresse :</strong> Esprit bloc IJK</p> <!-- Default address -->
        </div>

        <div class="actions">
    <a href="{{ path('user_modifieradmin', {'id': user.idUser}) }}" class="btn btn-primary">
        <i class="fas fa-edit"></i> Modifier le compte
    </a>

    <form method="post" action="{{ path('user_delete_self') }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer votre compte ?');">
        <button type="submit" class="btn btn-danger">
            <i class="fas fa-user-slash"></i> Supprimer mon compte
        </button>
    </form>
</div>

    {% else %}
        <div class="text-center">Aucun utilisateur trouvé.</div>
    {% endif %}
</div>
{% endblock %}